# Generated by Django 2.0.1 on 2018-10-16 03:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_data_datadescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='exp',
            new_name='expid',
        ),
        migrations.AddField(
            model_name='data',
            name='related_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='expdescription',
            field=models.CharField(default='experiment description', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='expendd',
            field=models.DateField(default='2018-11-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='expstartd',
            field=models.DateField(default='2018-02-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='generated_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='outcomes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='related_exps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
