# Generated by Django 2.0.1 on 2018-10-16 03:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20181016_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('outid', models.IntegerField(primary_key=True, serialize=False)),
                ('outtype', models.CharField(max_length=50)),
                ('outdescription', models.CharField(max_length=400)),
                ('related_out', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('expid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Experiment')),
            ],
        ),
    ]
