# Generated by Django 2.0.1 on 2018-10-16 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_participant_participant_experiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipid', models.IntegerField(primary_key=True, serialize=False)),
                ('equipname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantExperiment',
            fields=[
                ('exp_partid', models.IntegerField(primary_key=True, serialize=False)),
                ('expid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Experiment')),
                ('partid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Participant')),
            ],
        ),
        migrations.RemoveField(
            model_name='participant_experiment',
            name='expid',
        ),
        migrations.RemoveField(
            model_name='participant_experiment',
            name='partid',
        ),
        migrations.RemoveField(
            model_name='data',
            name='expid',
        ),
        migrations.DeleteModel(
            name='Participant_Experiment',
        ),
    ]
