# Generated by Django 2.0.1 on 2018-10-16 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20181016_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='exp_partid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.ParticipantExperiment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='expid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.Experiment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='quipid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.Equipment'),
            preserve_default=False,
        ),
    ]
