# Generated by Django 2.0.1 on 2018-10-17 04:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_experiment_experimenters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='generated_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='outcomes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='related_exps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
