# Generated by Django 2.0.1 on 2018-10-22 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_auto_20181017_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExperiment',
            fields=[
                ('usr_expid', models.AutoField(primary_key=True, serialize=False)),
                ('expid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Experiment')),
                ('usrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='dataid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='outid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='partid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participantexperiment',
            name='exp_partid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
