# Generated by Django 2.0.1 on 2019-01-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_remove_data_expid'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='upload',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
