# Generated by Django 2.0.1 on 2019-02-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_data_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedData',
            fields=[
                ('updataid', models.AutoField(primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
